apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openmetadata
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.open-metadata.org
      chart: openmetadata
      targetRevision: 1.5.4
      helm:
        valueFiles:
          - $values/charts/openmetadata/values-local.yaml
    - repoURL: https://github.com/cicerojmm/treinamentoLakehouseOpenSourceAWS
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: governance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
