apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airbyte-fix-path-style
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["airbyte-airbyte-env"]
    verbs: ["get", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["airbyte-server", "airbyte-worker"]
    verbs: ["get", "patch"]
