name: movielens
version: "1.0.0"
config-version: 2

profile: movielens

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  movielens:
    staging:
      +materialized: ephemeral
    silver:
      +schema: silver
      +materialized: table
    gold:
      +schema: gold
      +materialized: table
