apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airbyte-fix-path-style
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: default
  source:
    repoURL: https://github.com/cicerojmm/treinamentoDataHandsLakehouseOpenSourceAWS
    targetRevision: HEAD
    path: charts/airbyte-fix-path-style
  destination:
    server: https://kubernetes.default.svc
    namespace: ingestion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
