apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airbyte
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: default
  source:
    repoURL: https://airbytehq.github.io/helm-charts
    chart: airbyte
    targetRevision: 1.8.5
    helm:
      skipCrds: true
      parameters:
        - name: global.jobs.resources.requests.cpu
          value: "0"
        - name: global.jobs.resources.requests.memory
          value: "0"
      values: |
        global:
          database:
            host: airbyte-postgres.ingestion.svc.cluster.local
            port: 5432
            database: airbyte
            user: airbyte
            password: airbyte123
          storage:
            type: s3
            storageSecretName: airbyte-storage-secret
            bucket:
              log: airbyte-storage
              state: airbyte-storage
              workloadOutput: airbyte-storage
            s3:
              region: ""
              authenticationType: credentials

        webapp:
          enabled: true
          replicaCount: 1
          service:
            type: NodePort
            nodePort: 30088
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

        server:
          enabled: true
          replicaCount: 1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

        worker:
          enabled: true
          replicaCount: 1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi

        temporal:
          enabled: true
          replicaCount: 1

        postgresql:
          enabled: false

        minio:
          enabled: false

        airbyteBootloader:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: ingestion
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: airbyte-minio
      jsonPointers:
        - /spec
    - group: ""
      kind: ConfigMap
      name: airbyte-airbyte-env
      jsonPointers:
        - /data/MINIO_ENDPOINT
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - SkipDryRunOnMissingResource=true
      - PruneLast=true
