apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-postgres
  namespace: argocd
  labels:
    environment: eks
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 16.4.15
    helm:
      values: |
        fullnameOverride: airflow-postgres
        auth:
          database: airflow
          username: airflow
          password: airflow123
        primary:
          persistence:
            size: 10Gi
            storageClass: gp3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: ingestion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
