apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hive-metastore
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/OWNER/REPO.git
    targetRevision: main
    path: charts/hive-metastore/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: data-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
