apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-eks-setup
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/cicerojmm/treinamentoDataHandsLakehouseOpenSourceAWS
    targetRevision: HEAD
    path: charts/minio-eks-setup
  destination:
    server: https://kubernetes.default.svc
    namespace: data-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
