apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: airflow
  namespace: observability
  labels:
    app: airflow
spec:
  namespaceSelector:
    matchNames:
      - orchestration
  selector:
    matchLabels:
      component: webserver
  endpoints:
    - port: airflow-ui
      path: /health
      interval: 30s
