# OpenMetadata values for local environment

openmetadata:
  config:
    authentication:
      provider: basic
    database:
      host: openmetadata-postgres.governance.svc.cluster.local
      port: 5432
      driverClass: org.postgresql.Driver
      dbScheme: postgresql
      databaseName: openmetadata
      auth:
        username: openmetadata
        password:
          secretRef: openmetadata-postgres-secret
          secretKey: POSTGRES_PASSWORD
    elasticsearch:
      host: opensearch-cluster-master.governance.svc.cluster.local
      port: 9200
      scheme: http

ingress:
  enabled: false

airflow:
  enabled: true
  airflow:
    auth:
      username: admin
      password:
        secretRef: openmetadata-airflow-secret
        secretKey: password

postgresql:
  enabled: false

elasticsearch:
  enabled: false
