apiVersion: v1
kind: Secret
metadata:
  name: openmetadata-airflow-postgres-secret
  namespace: governance
type: Opaque
stringData:
  POSTGRES_USER: airflow_user
  POSTGRES_PASSWORD: airflow_pass
  POSTGRES_DB: airflow_db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openmetadata-airflow-postgres-pvc
  namespace: governance
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmetadata-airflow-postgres
  namespace: governance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openmetadata-airflow-postgres
  template:
    metadata:
      labels:
        app: openmetadata-airflow-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: openmetadata-airflow-postgres-secret
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 384Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: openmetadata-airflow-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: openmetadata-airflow-postgres
  namespace: governance
spec:
  selector:
    app: openmetadata-airflow-postgres
  ports:
    - port: 5432
      targetPort: 5432
